name: Node js app deploy to Kubernetes
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]   

jobs:
  ECR-Repo-Build:
    name: Deploy to ECR Repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
        id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: devopshint
        IMAGE_TAG: 1.1
        AWS_DEFAULT_REGION: eu-west-2 
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  
  Deploy-To-EC2:
    name: Deploy Kubernetes configuration to EC2
    runs-on: ubuntu-latest

    steps:  
    - name: Connect to Server
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOSTNAME: ${{secrets.SSH_HOST}}
        USER_NAME: ${{secrets.USER_NAME}}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_USER}
    
    - name: Add Deployment to EC2
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: devopshint
        IMAGE_TAG: 1.1
        AWS_DEFAULT_REGION: eu-west-2
      run: |
        sudo apt update
        sudo apt install awscli -y
        sudo $(aws ecr get-login --no-include-email --region eu-west-2);
        sudo kubectl apply -f deployment.yaml
        sudo kubectl apply -f service.yaml
        sudo kubectl apply -f pod.yaml
