name: Node js app deploy to Kubernetes
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
  REPOSITORY: devopshint
  IMAGE_TAG: 1.1    

jobs:
  build:
    name: Deploy to ECR Repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.27.0' # default is latest stable
        id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: devopshint
        IMAGE_TAG: 1.1
        AWS_DEFAULT_REGION: eu-west-2 
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

jobs:
  build:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
        
    steps:
    - name: Deploy Kubernetes configuration to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: devopshint
        IMAGE_TAG: 1.1
        AWS_DEFAULT_REGION: eu-west-2 
        SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${ { secrets.HOST_DNS }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        TARGET: ${ { secrets.TARGET_DIR }}
      run: |
        sudo apt update
        sudo apt install awscli -y
        sudo $(aws ecr get-login --no-include-email --region eu-west-2);
        sudo kubectl apply -f deployment.yaml
        sudo kubectl apply -f service.yaml
        sudo kubectl apply -f pod.yaml
